
  final Map<String, String> topicImages = {
    'Animals': 'assets/images/animals.jpeg',
    'Jobs': 'assets/images/jobs.jpeg',
    'Mekla': 'assets/images/mekla.jpeg',
    'Sports': 'assets/images/sport.jpeg',
    'Countries': 'assets/images/countries.jpeg',
    'Transportation': 'assets/images/transport.jpeg',
    'Football Players': 'assets/images/footballers.jpeg',
    'Actors': 'assets/images/actors.jpeg',
  };
  

final Map<String, List<String>> topics = {
    'Animals': [
      'Lion',      'Elephant',      'Giraffe',      'Monkey',      'Tiger',      'Zebra',      'Kangaroo',      'Penguin',
      'Dolphin',      'Panda',      'Cheetah',      'Koala',      'Hippopotamus',      'Raccoon',      'Gorilla',      'Koala',
      'Polar Bear',      'Leopard',      'Jaguar',      'Armadillo',      'Sloth',      'Crocodile',
      'Cobra',      'Giraffe',      'Penguin',      'Lynx',      'Platypus',      'Grizzly Bear',      'Ostrich',      'Red Fox',
      'Walrus',      'Rhinoceros',      'Antelope',      'Moose',      'Pangolin',      'Koala',
      'Penguin',      'Jaguar',      'Ocelot',      'Giraffe','Chameleon',      'Hedgehog',      'Lynx',      'Panda',      'Quokka',      'Alpaca',
      'Penguin',      'Elephant'
    ],
    'Jobs': [
      'Doctor',      'Engineer',      'Teacher',      'Programmer',      'Chef',      'Artist',
      'Pilot',      'Scientist',      'Police Officer',      'Firefighter',      'Nurse',      'Dentist',
      'Architect',      'Electrician',      'Plumber',      'Journalist',      'Actor',      'Librarian',
      'Psychologist',      'Veterinarian',      'Graphic Designer',      'Mechanic',      'Barista',      'Photographer',
      'Banker',      'Writer',      'Athlete',      'Cashier',      'Fashion Designer',      'Dancer',      'Fisher',
      'Painter',      'Pharmacist', 'Social Worker',      'Truck Driver', 'Waiter/Waitress',      'Zookeeper',      'Electrician',      'Farmer',      'Hairdresser',      'Judge',      'Lifeguard',      'Miner',      'Optometrist',      'Taxi Driver',
      'Translator',      'Usher',      'Videographer',      'X-ray Technician',      'Yoga Instructor',      'Zoologist'
    ],
    'Mekla': [
      'Mloukhiya',      'Lasagna',      'Ma9rouna',      '3ejja',      'Lablebi',      'Tastira',      'Mar9et 5odhra',
      'Gnewiya',      'Kafteji',      'Hargma',      'Mlewi',      'Chappati',      '3sida',      'Kosksi',
      'Ma9loub',      'Libanais',      'Bérzgène',      'Ba9lewa',      'Samsa',      'Merguez',      'Chorba',      'Tajin',      'Brik',
      'Tajin el bay',      'Mermez',      'Mar9et Jelbena',      'M7omsa',      'Masfouf',      'Chakchouka'
    ],
    'Sports': [
      'Football',      'Basketball',      'Baseball',      'Tennis',      'Golf',      'Cricket',
      'Rugby',      'Volleyball',      'Table Tennis',      'Hockey',      'Badminton',      'Boxing',
      'Martial Arts',      'Swimming',      'Cycling',     'Running',      'Skiing',      'Snowboarding',
      'Surfing',      'Skateboarding',      'Wrestling',      'Gymnastics',      'Rowing',
      'Sailing',      'Diving',      'Horseback Riding',      'Fencing',      'Triathlon',      'Archery',
      'Curling',      'Motorsport',      'Weightlifting',      'Softball',      'Water Polo',      'Canoeing',
      'Taekwondo',      'Handball',      'Judo',      'Polo',      'Climbing',      'Shooting',      'Biathlon',
      'Equestrian',      'Modern Pentathlon'
    ],
    'Countries': [
      'United States',
      'Canada',
      'Germany',
      'Japan',
      'Brazil',
      'Australia',
      'France',
      'India',
      'Italy',
      'Mexico',
      'Russia',
      'China',
      'South Africa',
      'Spain',
      'Argentina',
      'United Kingdom',
      'South Korea',
      'Nigeria',
      'Egypt',
      'Saudi Arabia',
      'Turkey',
      'Thailand',
      'Vietnam',
      'Indonesia',
      'Greece',
      'Norway',
      'Kenya',
      'New Zealand',
      'Peru',
      'Sweden',
      'Switzerland',
      'Ireland',
      'Chile',
      'Portugal',
      'Israel',
      'Belgium',
      'Denmark',
      'Finland',
      'Austria',
      'Czech Republic',
      'Hungary',
      'Netherlands',
      'Poland',
      'Romania',
      'Singapore',
      'Malaysia',
      'Philippines',
      'Pakistan',
      'Bangladesh'
    ],
    'Transportation': [
      'Car',
      'Bus',
      'Train',
      'Bicycle',
      'Motorcycle',
      'Airplane',
      'Boat',
      'Subway',
      'Helicopter',
      'Scooter',
      'Truck',
      'Taxi',
      'Ferry',
      'Rocket',
      'Segway',
      'Hot Air Balloon',
      'Rickshaw',
      'Gondola',
      'Jet Ski',
      'Space Shuttle',
      'Electric Scooter',
      'Ambulance',
      'Fire Truck',
      'Police Car',
      'Tram',
      'Zeppelin',
      'Unicycle',
      'Hang Glider',
      'Canoe',
      'Wheelchair',
      'Roller Skates',
      'RV',
      'Moped',
      'Cruise Ship',
      'Monster Truck',
      'Blimp',
      'Dog Sled',
      'Snowmobile',
      'Zipline',
      'Camper Van',
      'Snowboard',
      'Tank',
      'Jetpack',
      'Submarine',
      'Segway',
      'Go-Kart',
      'Snowplow'
    ],
    'Football Players': [
      'Pele',      'Diego Maradona',
      'Johan Cruyff',      'Franz Beckenbauer',      'George Best',      'Michel Platini',      'Zinedine Zidane',
      'Bobby Charlton',      'Ferenc Puskas',      'Garrincha',      'Eusebio',      'Alfredo Di Stefano',      'Lev Yashin',      'Bobby Moore',
      'Paolo Rossi',      'Ronaldo Nazario',      'Zico',      'Marco van Basten',      'Karl-Heinz Rummenigge',
      'Ruud Gullit',      'Andres Iniesta',      'Xavi Hernandez',      'Cristiano Ronaldo',      'Lionel Messi',      'Neymar Jr.',      'Kylian Mbappe',      'Robert Lewandowski',
      'Mohamed Salah',      'Luis Suarez',      'Sergio Ramos',      'Virgil van Dijk',
      'Kevin De Bruyne',      'Harry Kane',      'Andrea Pirlo',      'Thierry Henry',      'Luka Modric',      'Fernando Peyroteo',      'George Weah',
      'Rivaldo',      'Raul Gonzalez',      'David Beckham',      'Michael Owen',      'Gianluigi Buffon',      'Didier Drogba',      'Frank Lampard',      'Kaka',
      'Cesc Fabregas',      'Arjen Robben',      'Paolo Maldini',      'Gianfranco Zola',      'Alessandro Del Piero',      'Cafu',      'Iker Casillas',      'Steven Gerrard',
      'Patrick Vieira',      'Alessandro Nesta',      'Ronaldinho',      'Thierry Henry',      'Frank Rijkaard',      'Oliver Kahn',      'Gerd Muller',      'Sepp Maier',
      'Thomas Muller',      'Manuel Neuer',      'Bastian Schweinsteiger',      'Philipp Lahm',      'Miroslav Klose',      'Karl-Heinz Rummenigge',
      'Gerd Muller',      'Lothar Matthaus',      'Franz Beckenbauer',      'Paul Breitner',      'Uwe Seeler',      'Juergen Klinsmann',      'Jurgen Kohler',      'Andreas Brehme',
      'Pierre Littbarski',      'Helmut Haller',      'Wolfgang Overath',      'Bernd Schuster',      'Jupp Heynckes',      'Karl-Heinz Rummenigge'
    ],
    'Actors': [
      'Tom Hanks',
      'Leonardo DiCaprio',
      'Meryl Streep',
      'Denzel Washington',
      'Johnny Depp',
      'Robert De Niro',
      'Cate Blanchett',
      'Julia Roberts',
      'Brad Pitt',
      'Angelina Jolie',
      'Will Smith',
      'Jennifer Lawrence',
      'Morgan Freeman',
      'Joaquin Phoenix',
      'Natalie Portman',
      'Charlize Theron',
      'Christian Bale',
      'Kate Winslet',
      'Scarlett Johansson',
      'Matthew McConaughey',
      'Viola Davis',
      'Tom Cruise',
      'Daniel Day-Lewis',
      'Emma Stone',
      'Chris Hemsworth',
      'Anne Hathaway',
      'Keanu Reeves',
      'Harrison Ford',
      'Nicole Kidman',
      'Ryan Gosling',
      'Emma Watson',
      'Jake Gyllenhaal',
      'Mark Wahlberg',
      'Samuel L. Jackson',
      'Hugh Jackman',
      'Russell Crowe',
      'Jessica Chastain',
      'Daniel Radcliffe',
      'Dwayne Johnson',
      'Eddie Redmayne',
      'Chris Pratt',
      'Gal Gadot',
      'Ryan Reynolds',
      'Bradley Cooper',
      'Sandra Bullock',
      'Amy Adams',
      'Idris Elba',
      'Eva Green',
      'Javier Bardem',
      'Ewan McGregor',
      'Judi Dench',
      'Michael Fassbender',
      'Benedict Cumberbatch',
      'Mahershala Ali',
      'Cillian Murphy',
      'Matthew Damon',
      'Anne Hathaway',
      'Lupita Nyong\'o',
      'Woody Harrelson',
      'Oscar Isaac',
      'Antonio Banderas',
      'Julianne Moore',
      'Daniel Craig',
      'Colin Firth',
      'Emily Blunt',
      'Helen Mirren',
      'Steve Carell',
      'Tilda Swinton',
      'Gary Oldman',
      'Ethan Hawke',
      'Jesse Eisenberg',
      'Tom Hardy',
      'Timothée Chalamet',
      'Jamie Foxx',
      'Reese Witherspoon',
      'Chris Evans',
      'Robert Downey Jr.',
      'Brie Larson',
      'Chadwick Boseman'
    ],
  };
